# Generated by Django 6.0.1 on 2026-01-21 13:10

import Ticketapp.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('Ticket_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(help_text='Tittel på din henvendelse', max_length=150)),
                ('Description', models.TextField()),
                ('Status', models.CharField(choices=[('O', 'åpen'), ('U', 'under arbeid'), ('C', 'lukket')], max_length=1)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Changed_at', models.DateTimeField(auto_now=True)),
                ('Deadline', models.DateField(default=Ticketapp.models.get_default_deadline)),
                ('Casemanager_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
