# Generated by Django 6.0.1 on 2026-01-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticketapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='Status',
            field=models.CharField(choices=[('O', 'åpen'), ('U', 'under arbeid'), ('C', 'lukket')], default='O', max_length=1),
        ),
    ]
